version: '2'
services:
  # Database
  postgres:
    image: quay.io/azavea/postgis:9.4.4
    env_file: .env
    ports:
      - "5432:5432"

  app-frontend:
    image: node:4.4.7-wheezy
    working_dir: /opt/raster-foundry/app-frontend/
    volumes:
      - ./app-frontend/.babelrc:/opt/raster-foundry/app-frontend/.babelrc
      - ./app-frontend/config/:/opt/raster-foundry/app-frontend/config/
      - ./nginx/srv/dist/:/opt/raster-foundry/app-frontend/dist/
      - ./app-frontend/.eslintrc:/opt/raster-foundry/app-frontend/.eslintrc
      - ./app-frontend/karma.conf.js:/opt/raster-foundry/app-frontend/karma.conf.js
      - ./.node_modules:/opt/raster-foundry/app-frontend/node_modules
      - ./app-frontend/package.json:/opt/raster-foundry/app-frontend/package.json
      - ./app-frontend/src:/opt/raster-foundry/app-frontend/src
      - ./app-frontend/webpack.config.js:/opt/raster-foundry/app-frontend/webpack.config.js
    command: npm run build-watch

  app-server:
    image: quay.io/azavea/scala:2.11.8
    links:
      - postgres:database.raster-foundry.internal
    env_file: .env
    ports:
      - "9000:9000"
    volumes:
      - ./app-server/:/opt/raster-foundry/app-server/
      - ./.ivy2:/root/.ivy2
      - ./.sbt:/root/.sbt
    working_dir: /opt/raster-foundry/app-server/
    command: ./sbt app/run

  swagger-editor:
    image: swaggerapi/swagger-editor:latest
    ports:
      - "8080:8080"

  nginx:
    image: nginx
    ports:
      - "9100:443"
    links:
      - app-server
    volumes:
      - ./nginx/srv/dist/:/srv/dist/
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
