version: '2'
services:
  nginx:
    image: raster-foundry-nginx:${GIT_COMMIT}
    build:
      context: ./nginx
      dockerfile: Dockerfile

  app-server:
    image: raster-foundry-app-server:${GIT_COMMIT}
    build:
      context: ./app-server/app
      dockerfile: Dockerfile

  airflow:
    image: raster-foundry-airflow:${GIT_COMMIT}
    build:
      context: ./app-tasks
      dockerfile: Dockerfile
    volumes:
      - ./app-tasks/rf/:/opt/raster-foundry/app-tasks/rf/
