---
- name: Restart Vagrant
  service: name=vagrant state=restarted
  when: "['app-servers', 'workers'] | some_are_in(group_names)"

- name: Restart rf-app
  service: name=rf-app state=restarted
  when: "['app-servers'] | is_in(group_names)"

- name: Restart rf-worker
  service: name=rf-worker state=restarted
  when: "['workers'] | is_in(group_names)"
