---
- name: Touch log file if it does not exist
  command: touch {{ log_path }}
           creates={{ log_path }}

- name: Set log file permissions
  file: path={{ log_path }}
        owner=rf
        group=rf
        mode=0664

- name: Configure log rotation
  template: src=logrotate-worker.j2
            dest=/etc/logrotate.d/rf-worker
