---
- name: Copy AWS Credentials
  copy: src=~/.aws dest=/var/lib/rf owner=rf

- name: Create EC2 style temp directory
  file: path="{{ temp_dir }}"
        owner=rf
        group=rf
        mode=0755
        state=directory
