---
- name: Create Django database cache table
  django_manage: command=createcachetable
                 cache_table="rf_cache"
                 app_path="{{ django_home }}"
  environment: "{{ envdir_config | combine(django_config) }}"
  sudo: False
  when: "['development', 'test'] | some_are_in(group_names)"

- name: Run Django database migrations
  django_manage: command=migrate
                 app_path="{{ django_home }}"
  environment: "{{ envdir_config | combine(django_config) }}"
  sudo: False
  when: "['development', 'test'] | some_are_in(group_names)"
