---
- hosts: app-servers
  sudo: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - { role: "raster-foundry.app" }
    - { role: "raster-foundry.mock-geoprocessing", when: "['development', 'test'] | some_are_in(group_names)" }
