---
- hosts: template
  sudo: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes cache_valid_time=3600

  roles:
    # e.g. - { role: "raster-foundry.postgresql", when: "['development', 'test'] | some_are_in(group_names)" }
